import Head from 'next/head'
import Image from "next/image";
import {Header} from "../components/Header";
import {Footer} from "../components/Footer";
import {MicrophoneIcon, SearchIcon} from "@heroicons/react/solid";
import {useRouter} from "next/router";
import {useRef} from "react";

const Home = () => {
    const router = useRouter();
    const searchInputRef = useRef(null);

    function search(event) {
        event.preventDefault();
        const term = searchInputRef.current.value;
        if (!term.trim()) return;
        router.push(`/search?term=${term.trim()}&searchType=`);
    }

    async function randomSearch(event) {
        event.preventDefault();
        const randomTerm = await fetch(
            "https://random-word-api.herokuapp.com/word?number=1"
        ).then((response) => response.json());
        if (!randomTerm) return;
        router.push(`/search?term=${randomTerm}&searchType=`);
    }

    return (
        <div>
            <Head>
                <title>DK Google Clone</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <div className="bg-[#202124] text-[#e8eaed]">
                <Header/>

                <form className="flex flex-col items-center mt-40 min-h-[70vh] lg:mt-60 lg:min-h-[60vh] xl:mt-70 ">
                    <Image
                        width="300"
                        objectFit="cover"
                        height="100"
                        alt="Google Icon"
                        src="https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Google_2015_logo.svg/1200px-Google_2015_logo.svg.png"
                    />
                    <div
                        className="flex w-full mt-5 mx-auto max-w-[90%] border border-gary-200 hover:shadow-lg focus-within:shadow-lg px-5 py-3 rounded-full items-center sm:max-w-xl lg:max-w-2xl">
                        <SearchIcon className="h-5 text-[#9aa0a5] mr-3"/>

                        <input
                            ref={searchInputRef}
                            type="text"
                            className="flex-grow bg-[#202124] focus:outline-none"
                        />
                        <MicrophoneIcon className="h-5 text-[#9aa0a5]"/>
                    </div>
                    <div
                        className="flex flex-col sm:flex-row w-[50%] space-y-2 mt-8 sm:space-y-0 sm:space-x-4 justify-center">
                        <button onClick={search} className="btn">
                            Google Search
                        </button>
                        <button onClick={randomSearch} className="btn">
                            I&apos;m Feeling Lucky
                        </button>
                    </div>
                </form>

                <Footer/>
            </div>
        </div>
    )
}

export default Home;