import Head from 'next/head'
import {Header} from "../components/Header";

export const Home = () => {
  return (
    <div>
      <Head>
        <title>DK Google Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

        <Header />

    </div>
  )
}

export default Home;